services:
  app:
    build: .
    ports:
      - "3038:3038"
    environment:
      - PORT=3038
      - DATABASE_URL=postgresql://admin:securepassword@db:5432/hospital_db?schema=public
      - JWT_SECRET=hospital_management_secure_key_2024
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: hospital_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
