name: Hospital App CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run Priority Logic Test
        run: node tests/patient.test.js

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to CloudPanel via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/s2140775-node/htdocs/s2140775n.ncgrp.xyz/hospital-app
            git pull origin main
            
            echo "Rebuilding container blocks..."
            docker compose down --remove-orphans
            docker compose up --build -d
            
            echo "Allowing system instances to settle..."
            sleep 10
            
            echo "Forcing dynamic relational database table migration and seed updates..."
            NODE_OPTIONS="--max-old-space-size=128" docker compose exec -T app npx prisma db push --accept-data-loss --skip-generate
            NODE_OPTIONS="--max-old-space-size=128" docker compose exec -T app npx prisma db seed
